### ISSUE TITLE
flyspell-duplicate has incorrect spec 

### ISSUE THREAD

**Issue by CarlsonP4** [alezost/alect-themes#13]
`         (flyspell-duplicate     ((,c :foreground ,(gc 'gray)
                                      :background ,(gc 'bg))
                                      :weight bold))
`
I think this should be:
`         (flyspell-duplicate     ((,c :foreground ,(gc 'gray)
                                      :background ,(gc 'bg)
                                      :weight bold)))
`

**Comment by alezost** [comment]
Ouch, fixed by commit 588eb9ef66c319705a4d94003eacd90ad9de29c2.  Thank you!
