### ISSUE TITLE
alect-ignored-faces itself ignored in use-package stanza

### ISSUE THREAD

**Issue by jdtsmith** [alezost/alect-themes#15]
I've long setup some ignored faces like:

```elisp
(use-package alect-themes
  :ensure t
  :init
  (setq alect-ignored-faces		;leave these as per defaults
	'(font-lock-comment-face
	  font-lock-string-face
	  font-lock-keyword-face
	  font-lock-function-name-face
	  font-lock-variable-name-face
	  font-lock-constant-face
	  info-title-1 info-title-2
	  info-title-3 info-title-4))
  :config
  (load-theme 'alect-dark t)
...
...
```

which has always worked fine.  But after recently updating alect-themes, I find these faces are _not_ ignored.  If I later (re-)load the alect-dark theme, these faces are ignored correctly, but not sadly on the first pass.  Thanks for this great theme.

**Comment by jdtsmith** [comment]
Answering myself: the updated package had a different SHA256, and rather than error, was getting only partially loaded.  I needed to remove the `t` from the load-theme above, restart, trust the theme as safe, and then re-insert it.

**Comment by jdtsmith** [comment]
OK spoke too soon.  If I include the `t` in `load-theme` for `no-confirm`, the faces are _not_ ignored.  If I remove the `t`, and go through the prompt regarding safety of the mode, ignored-faces is respected.  Not sure why this would be.

**Comment by jdtsmith** [comment]
OK figured this out: `no-confirm` option of load-theme switches between loading the pre-compiled file, and evaluating the file (after confirming it's SHA256 hash).   Since the files had been compiled without `alect-ignored-faces` configured, and that variable is used by a _macro_ (i.e. expanded at compile time), that caused the difference.  

Solution?  Delete all the `~/.emacs/elpa/alect*/*.elc` files.

**Comment by alezost** [comment]
Oops, sorry that I missed this issue.
Thank you for the descriptive explanation and your solution!

I see that this problem may arise for other people.
I am not sure if I can do anything to fix it on alect-themes side though :(

**Comment by jdtsmith** [comment]
In fact I just decided to nuke my `.emacs/elpa` directory and let it reinstall from scratch, and the same issue recurred.  The problem is that the package installer pre-compiles the files on download.  The solution is to alter the load so it respects `alect-ignored-faces` at run-time instead of just compile time.  This would also be useful for people who want to play around with that variable.
