### ISSUE TITLE
New faces

### ISSUE THREAD

**Issue by thbrcr** [alezost/alect-themes#2]
It would be great to have faces for Tuareg (and Caml/OCaml by inheritence), as well as utop and merlin. Also, faces for cperl-mode.

Very few themes support those modes and it would made a great differential/addition to alect-themes to support those.

**Comment by alezost** [comment]
Thanks for the suggestion, I'll look into these modes soon.

**Comment by alezost** [comment]
OK, so I've added support for tuareg, merlin, utop and cperl.

A couple of problems I faced: as my distribution doesn't provide
packages for merlin and utop, I themed the faces of merlin and utop
emacs packages blindly (I beg a pardon, but I didn't bother to compile
those prorgams from source), so if you find that something is blatantly
ugly, please let me now (screenshots are appreciated).

Also I didn't find where `caml-types-expr-face`,
`caml-types-typed-face`, `caml-types-scope-face`, `caml-types-def-face`
and `caml-types-occ-face` are used, and unlike merlin/utop I can't even
guess the context.

However there is a real problem with these faces: they **can't be
customized** at all (with any theme).  As you can see in
[caml-types.el](http://caml.inria.fr/svn/ocaml/trunk/emacs/caml-types.el),
these faces are not defined in the usual manner via `defface`, but using
`make-face` function instead, which leads to the impossibility of being
themed.

For example, you may check `M-x customize-face RET caml-types-def-face`:
do you see "NO CUSTOMIZATION DATA; not intended to be customized."?
That's not good :-)

By the way, `C-h f make-face` tells:

    Do not call this directly from Lisp code; use `defface' instead.

So someone who is interested should probably contact with the
maintainers of the caml emacs package and report about this problem.

**Comment by thbrcr** [comment]
I tested and everything looks great! Merlin (and utop) doesn't look ugly at all, specially Merlin's error check which by default used awful colors now displays erros in bold red, much more pleasing and easy to scan.

Don't bother about caml-mode type faces, they're just legacy cruft and, as far as I know, it's only a dependency for Tuareg since there's shared code.

Thank you so much for providing these faces so quickly! Really good job.

**Comment by alezost** [comment]
OK, thanks for the feedback!  Closing this issue.
