### ISSUE TITLE
mu4e face

### ISSUE THREAD

**Issue by tsdye** [alezost/alect-themes#4]
Aloha Alex,
I recently started using a new email client, mu4e.  The face, mu4e-header-highlight-face, is used extensively by mu4e, but shows up poorly using alect light.  The dark theme is OK, but the light theme is somewhat hard to use.  Here is a screen shot:
![mu4e](https://cloud.githubusercontent.com/assets/125573/9001595/2df37984-36f5-11e5-92c2-13520505238e.jpg)

All the best,
Tom

**Comment by alezost** [comment]
Hello Tom,
Sorry for the delay.  For some reason I didn't get the notification about this issue.  I'm going to look at mu4e faces in a couple of days.  Thank you for the screen shot.

**Comment by alezost** [comment]
I've just added support for mu4e.  Let me know if you notice
anything you think should be improved.

Aloha

**Comment by tsdye** [comment]
Aloha Alex,

Nice!  Many thanks.

All the best,
Tom

Alex Kost <notifications@github.com> writes:

> I've just added support for mu4e.  Let me know if you notice
> anything you think should be improved.
>
> Aloha
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alezost/alect-themes/issues/4#issuecomment-128094991

-- 
Thomas S. Dye
http://www.tsdye.com
