### ISSUE TITLE
Can't read my input text in view describe-variable in alect-black [spacemacs]

### ISSUE THREAD

**Issue by rapphammar** [alezost/alect-themes#5]
First, Thanks for a great theme.

Using spacemacs
To reproduce:
set theme to alect-black
<F1>-v (describe variable)
start typing something to filter the list (spacemacs--cur-theme)
the fg and bg are very similar and can't be read (beige).

**Comment by alezost** [comment]
(Holy Moly, I've just tried Spacemacs :smile:)

Hello, if I understand you correctly (probably not), you don't see what
you type in the mode-line, right? (see the screenshot)

http://i.imgur.com/o7d7kMH.png

If so, I see the same **with any theme**.  After some investigating I found
that it comes from helm: when `helm-echo-input-in-header-line` is set to
`t` (which is the spacemacs default), both background and foreground are
set to the same color (see [helm-hide-minibuffer-maybe](https://github.com/emacs-helm/helm/blob/master/helm.el#L3760-L3769) function).

To see the minibuffer again, you need:

``(setq helm-echo-input-in-header-line nil)``

But the word `beige` confuses me (as the mode-line is black).  Did you mean anything else?

**Comment by rapphammar** [comment]
Looks like this was due to me trying a lot of themes before settling on your, 
restarting with default theme set fixed it.

Posting my messed up window just for reference, consider it closed.
http://imgur.com/a/jocIo

Thanks for a quick reply.

**Comment by alezost** [comment]
Thanks for the screenshot, now I see what you meant.  I'm glad you figured it out.
