### ISSUE TITLE
change bg on the fly

### ISSUE THREAD

**Issue by rapphammar** [alezost/alect-themes#6]
Hey Alex,

is there a way to create a defun that changes the main bg on the fly?

(in terminals I often use different bg depending on what I'm doing in this frame,
dark-green, dark-red, dark-blue,...
general emacs have set-background)

something like this, (though I'm unsure of what bgs need defined for just the main one) 

(defun jr-changeBg-green ()
  "set bg dark green"
  (interactive)
  ;(progn
    (alect-set-color 'dark 'bg "#002d00")
    (alect-set-color 'dark 'bg-1 "#002d00")
    (alect-set-color 'dark 'bg-2 "#002d00")
    ;)
  )

**Comment by alezost** [comment]
Hi!  Sorry for the delay, I've just noticed this issue :blush:

I don't fully understand your question.  If you want to change just the
background, then you can write your command like this:

```elisp
(defun jr-changeBg-green ()
  "set bg dark green"
  (interactive)
  (set-background-color "#002d00"))
```

Or do you mean something else?

**Comment by alezost** [comment]
Oh, if you mean you want to reload the theme after setting the
background (only `bg-1` is responsible for the default background), then
you can just use `load-theme`:

```elisp
(defun jr-changeBg-green ()
  "set bg dark green"
  (interactive)
  (alect-set-color 'dark 'bg-1 "#002d00")
  (load-theme 'alect-dark t))
```

BTW I'm very surprised you use these themes on terminal.  Don't they
look ugly there :smile:?  (I use only GUI Emacs so I never bothered to
support less colors)

**Comment by alezost** [comment]
@rapphammar ping :-)

Are you going to reply?  Otherwise I'll close this issue.

**Comment by rapphammar** [comment]
Sorry boss, didn't think about it since I solved it by adding columns with
alternate colors.

Close it..
