### ISSUE TITLE
Spacemacs status bar

### ISSUE THREAD

**Issue by tsdye** [alezost/alect-themes#7]
Aloha Alex,

I've been experimenting with spacemacs and noticed that the alect themes yield a funky looking status bar.  The attached screenshot shows the background box is too big (it extends down past the bottom edge of the status bar) and the font color makes for difficult reading.

All the best,
Tom

![alect](https://cloud.githubusercontent.com/assets/125573/21950667/62a3314c-d9a1-11e6-8c8b-3e9408888da5.jpg)

**Comment by alezost** [comment]
Hello Tom!

I don't use spacemacs or any mode-line modificators so it's hard to tell
where this face comes from.

I guess there is some package that modifies the standard mode-line.  Do
you use any such package (`smart-mode-line` or another one)?

**Comment by tsdye** [comment]
Aloha Alex,

Alex Kost writes:

> Hello Tom!
>
> I don't use spacemacs or any mode-line modificators so it's hard to tell
> where this face comes from.
>
> I guess there is some package that modifies the standard mode-line. Do
> you use any such package (smart-mode-line or another one)?
>

Spacemacs uses powerline, which is new to me.  The faces are
powerline-active1, powerline-active2, powerline-inactive1, and
powerline-inactive2.

I managed to fix the problem of the backgrounds extending outside the
modeline by changing the modeline separator from 'wave to nil, so I
guess that wasn't an alect font issue (though, I'm baffled why changing
to a non-alect theme got rid of that problem).

All the best,
Tom

--
Thomas S. Dye
http://www.tsdye.com

**Comment by alezost** [comment]
Hello Tom,

I have added support for powerline (i.e., there shouldn't be "black on
gray"), however I didn't have issues with the extended boxes that you
describe, so I don't know what could be the problem.  Any value of
`powerline-default-separator` works for me.  Here is how the mode-line
with powerline looks for me now:

![screenshot](http://i.imgur.com/EXs25st.png)

P.S.  As you can see, I use cyan background which is rather unusual for
alect themes, so I'm not sure it was a good idea.  Let me know if you
think it's not looking good.

**Comment by tsdye** [comment]
Aloha Alex,

Alex Kost writes:

> Hello Tom,
>
> I have added support for powerline (i.e., there shouldn't be "black on
> gray"), however I didn't have issues with the extended boxes that you
> describe, so I don't know what could be the problem.  Any value of
> `powerline-default-separator` works for me.  Here is how the mode-line
> with powerline looks for me now:
>
> ![screenshot](http://i.imgur.com/EXs25st.png)
>
> P.S.  As you can see, I use cyan background which is rather unusual for
> alect themes, so I'm not sure it was a good idea.  Let me know if you
> think it's not looking good.

Much better.  Thanks!

All the best,
Tom

--
Thomas S. Dye
http://www.tsdye.com
